const MAX_BODY = 60_000  # GitHub caps PR bodies at 65536 characters

link(doi) = "[$doi]($(doi_url(doi)))"
escape_md(s) = replace(s, r"([*_`\[\]<>])" => s"\\\1")

function team_label(a::Assessment)
    isempty(a.team) && return "no team author"
    return join((p.name for p in a.team), ", ")
end

function evidence_label(a::Assessment)
    parts = unique!(["$(e.package.name) ($(e.source))" for e in a.evidence])
    a.gpu && push!(parts, "GPU")
    a.julia && push!(parts, "Julia")
    acknowledged(a) && push!(parts, "acknowledges $(a.acknowledgment)")
    return isempty(parts) ? "none" : join(parts, "; ")
end

fulltext_label(a::Assessment) =
    a.fulltext == :pdf ? "PDF checked" : a.fulltext == :index ? "OpenAlex full-text index" : "full text not accessible"

function details(io, summary, body)
    println(io, "<details><summary>$summary</summary>\n")
    print(io, body)
    println(io, "\n</details>\n")
end

function weekly_report(assessments::Vector{Assessment}, swaps, cfg::Config; since::Date, nworks::Int)
    strong = filter(a -> a.bucket == :strong, assessments)
    review = filter(a -> a.bucket == :review, assessments)
    none = filter(a -> a.bucket == :none, assessments)
    io = IOBuffer()
    println(io, "## Publication scan ($(today()))\n")
    println(io, "Works published since $since by the $(length(cfg.people)) people in `_pubbot/people.toml`",
            cfg.citing_core ? ", plus works citing core stack packages" : "",
            ": $nworks records, $(length(assessments)) new papers after removing duplicates and already evaluated DOIs.\n")

    println(io, "### ✅ Added to publications.md ($(length(strong)))\n")
    isempty(strong) || println(io, "To drop an entry, delete its line in `publications.md` before merging; it will not be proposed again.\n")
    for a in strong
        println(io, "- **$(escape_md(a.work.title))** · $(link(a.work.doi))  \n  $(team_label(a)) · evidence: $(evidence_label(a)) · $(fulltext_label(a))")
    end
    println(io)

    if !isempty(swaps)
        println(io, "### 🔁 Preprints replaced by their published version ($(length(swaps)))\n")
        for s in swaps
            println(io, "- $(link(s.old)) → $(link(s.new)): $(escape_md(s.title))")
        end
        println(io)
    end

    println(io, "### 🟡 Needs review ($(length(review)))\n")
    if !isempty(review)
        println(io, "To add one, paste its line into `publications.md` on this branch.\n")
        body = IOBuffer()
        for a in review
            println(body, "- **$(escape_md(a.work.title))** · $(link(a.work.doi))  \n  $(team_label(a)) · evidence: $(evidence_label(a)) · $(fulltext_label(a))")
            a.entry === nothing ? println(body, "  _$(a.note)_") : println(body, "  ```md\n  $(a.entry)\n  ```")
        end
        details(io, "Show $(length(review)) papers", String(take!(body)))
    end

    footer = "---\nMerging records every DOI above in `_pubbot/seen_dois.txt`. Generated by `_pubbot/weekly.jl`.\n"
    println(io, "### ❌ No stack signal ($(length(none)))\n")
    if !isempty(none)
        # The collapsed list is the only part cut to fit GitHub's size limit.
        # Bytes, not characters: conservative for the character limit.
        budget = MAX_BODY - position(io) - ncodeunits(footer) - 500
        body = IOBuffer()
        shown = 0
        for a in none
            note = isempty(a.note) ? "" : " · $(a.note)"
            line = "- $(escape_md(a.work.title)) · $(link(a.work.doi)) · $(team_label(a)) · $(fulltext_label(a))$note\n"
            position(body) + ncodeunits(line) > budget && break
            print(body, line)
            shown += 1
        end
        shown < length(none) && println(body, "- … and $(length(none) - shown) more, run `_pubbot/weekly.jl --dry-run` locally for the full list")
        details(io, "Show $(length(none)) papers", String(take!(body)))
    end
    print(io, footer)
    return String(take!(io))
end

function add_report(added, skipped; issue=nothing)
    io = IOBuffer()
    println(io, "## Add publications\n")
    for (doi, entry) in added
        println(io, "- ✅ $(link(doi))\n  ```md\n  $entry\n  ```")
    end
    for (doi, reason) in skipped
        println(io, "- ⏭️ $(link(doi)): $reason")
    end
    isempty(added) && isempty(skipped) && println(io, "No DOI found in the request.")
    issue === nothing || println(io, "\nCloses #$issue")
    return String(take!(io))
end
